### PR TITLE
Add VTEX simulation handler on useCart

### PR DESCRIPTION
**Pull request by gustavo-vasconcellos**
### Added

- Types to SimulationOrderForm
- Handler to call simulation API on Client

### CODE REVIEW

**Review by lucis — COMMENTED** [review]
Great addition!

I think you changed some types from objects to string. Did you check if that didn't break any Cart implementation?

**Comment by gustavo-vasconcellos** [comment]
> Great addition!
> 
> I think you changed some types from objects to string. Did you check if that didn't break any Cart implementation?

Yes. The cart functions continue working. I think these values could be auto generated cause each store can send diferent values.

**Comment by lucis** [comment]
Great. What I mean is: before, the `shippingEstimate` returnes this type:
image


But you've changed it to return string.

I don't have the full context here to understand if that wan intentional (and we had the wrong typings before)

cc @tlgimenes

**Comment by lucis** [comment]
@gustavo-vasconcellos I've just checked with @tlgimenes and he said that the appropriate place to add this method would be in `useCart` hook (which is specifically for client-side queries, like the one you've made).

Could you move it there? https://github.com/deco-sites/std/blob/main/commerce/vtex/hooks/useCart.ts

**Review by tlgimenes — APPROVED** [review]
NICE!

**Review by lucis — APPROVED** [review]

**Pull request merged**
