### PR TITLE
feat: add dynamic autocomplete search count param

### PR DESCRIPTION
**Pull request by RenanHCosta**
This PR removes the fixed **"count"** param used in Autocomplete hook. This amplify the use of dynamic queries on components like a searchbar.

It alsos changes the params to more clear names, for better intellisense.

### CODE REVIEW

**Comment by jonathanwlopes** [comment]
Very cool, 
I went through the same problem, I hope it is merged.

**Comment by Brunight** [comment]
Same. Waiting for merge :)

**Comment by DanielGDC12** [comment]
Got stuck with the same issue , need this with a certain urgency

**Comment by IncognitaDev** [comment]
I need this too. Will be merged soon?

**Review by tlgimenes — APPROVED** [review]

**Comment by tlgimenes** [comment]
Thanks guys for the excitement around this PR. I'm merging it now. Sorry for taking so long. 

Also, congrats @RenanHCosta, awesome contribution!

**Pull request merged**
